/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Regenerate with: npm run ai:gen-schema
 * Source: prisma/schema.prisma
 *
 * Carries the facts the AI schema dictionary omits — allowed values for
 * status/type columns, scalar types, defaults and relation targets. Without the
 * allowed values the model emits `status: "available"` instead of "AVAILABLE"
 * and the query silently returns nothing.
 */

export interface GeneratedField {
  name: string;
  type: string;
  isList: boolean;
  isOptional: boolean;
  default?: string;
  enumValues?: string[];
  relationTo?: string;
  comment?: string;
}

export interface GeneratedModel {
  name: string;
  fields: GeneratedField[];
}

export const PRISMA_ENUMS: Record<string, string[]> = {
  "Role": [
    "SUPER_ADMIN",
    "ADMIN",
    "SALES_MANAGER",
    "AGENT",
    "HR",
    "LOGISTICS",
    "FINANCE",
    "RECEPTIONIST",
    "VIEWER"
  ]
};

export const PRISMA_MODELS: Record<string, GeneratedModel> = {
  Organization: {
    name: 'Organization',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false },
      { name: "domain", type: "String", isList: false, isOptional: true },
      { name: "logo", type: "String", isList: false, isOptional: true },
      { name: "description", type: "String", isList: false, isOptional: true },
      { name: "businessLocation", type: "String", isList: false, isOptional: true },
      { name: "phone", type: "String", isList: false, isOptional: true },
      { name: "email", type: "String", isList: false, isOptional: true },
      { name: "taxId", type: "String", isList: false, isOptional: true },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
      { name: "users", type: "User", isList: true, isOptional: false, relationTo: "User" },
      { name: "properties", type: "Property", isList: true, isOptional: false, relationTo: "Property" },
      { name: "leads", type: "Lead", isList: true, isOptional: false, relationTo: "Lead" },
      { name: "employeeProfiles", type: "EmployeeProfile", isList: true, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "clients", type: "Client", isList: true, isOptional: false, relationTo: "Client" },
      { name: "tasks", type: "Task", isList: true, isOptional: false, relationTo: "Task" },
      { name: "owners", type: "Owner", isList: true, isOptional: false, relationTo: "Owner" },
      { name: "documents", type: "Document", isList: true, isOptional: false, relationTo: "Document" },
      { name: "vehicles", type: "Vehicle", isList: true, isOptional: false, relationTo: "Vehicle" },
      { name: "chatRooms", type: "ChatRoom", isList: true, isOptional: false, relationTo: "ChatRoom" },
      { name: "calendarEvents", type: "CalendarEvent", isList: true, isOptional: false, relationTo: "CalendarEvent" },
      { name: "aiDocuments", type: "AiDocument", isList: true, isOptional: false, relationTo: "AiDocument" },
      { name: "aiChatSessions", type: "AiChatSession", isList: true, isOptional: false, relationTo: "AiChatSession" },
      { name: "aiMemoryVectors", type: "AiMemoryVector", isList: true, isOptional: false, relationTo: "AiMemoryVector" },
      { name: "integrationConfigs", type: "IntegrationConfig", isList: true, isOptional: false, relationTo: "IntegrationConfig" },
      { name: "communicationTemplates", type: "CommunicationTemplate", isList: true, isOptional: false, relationTo: "CommunicationTemplate" },
      { name: "integrationLogs", type: "IntegrationLog", isList: true, isOptional: false, relationTo: "IntegrationLog" },
      { name: "subscription", type: "Subscription", isList: false, isOptional: true, relationTo: "Subscription" },
      { name: "apiUsageLogs", type: "ApiUsageLog", isList: true, isOptional: false, relationTo: "ApiUsageLog" },
      { name: "aiPendingApprovals", type: "AiPendingApproval", isList: true, isOptional: false, relationTo: "AiPendingApproval" },
      { name: "aiActiveDrafts", type: "AiActiveDraft", isList: true, isOptional: false, relationTo: "AiActiveDraft" },
    ],
  },
  User: {
    name: 'User',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "email", type: "String", isList: false, isOptional: false },
      { name: "passwordHash", type: "String", isList: false, isOptional: false },
      { name: "firstName", type: "String", isList: false, isOptional: false },
      { name: "lastName", type: "String", isList: false, isOptional: true },
      { name: "role", type: "Role", isList: false, isOptional: false, default: "AGENT", enumValues: ["SUPER_ADMIN","ADMIN","SALES_MANAGER","AGENT","HR","LOGISTICS","FINANCE","RECEPTIONIST","VIEWER"] },
      { name: "isActive", type: "Boolean", isList: false, isOptional: false, default: "true" },
      { name: "isSystemAdmin", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
      { name: "assignedProperties", type: "Property", isList: true, isOptional: false, relationTo: "Property" },
      { name: "assignedLeads", type: "Lead", isList: true, isOptional: false, relationTo: "Lead" },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: true, relationTo: "EmployeeProfile" },
      { name: "clients", type: "Client", isList: true, isOptional: false, relationTo: "Client" },
      { name: "assignedTasks", type: "Task", isList: true, isOptional: false, relationTo: "Task" },
      { name: "assignedOwners", type: "Owner", isList: true, isOptional: false, relationTo: "Owner" },
      { name: "createdDocuments", type: "Document", isList: true, isOptional: false, relationTo: "Document" },
      { name: "versionedDocuments", type: "DocumentVersion", isList: true, isOptional: false, relationTo: "DocumentVersion" },
      { name: "keyCheckouts", type: "KeyCheckout", isList: true, isOptional: false, relationTo: "KeyCheckout" },
      { name: "chatRooms", type: "ChatRoom", isList: true, isOptional: false, relationTo: "ChatRoom" },
      { name: "messages", type: "Message", isList: true, isOptional: false, relationTo: "Message" },
      { name: "createdTasks", type: "Task", isList: true, isOptional: false, relationTo: "Task" },
      { name: "createdEvents", type: "CalendarEvent", isList: true, isOptional: false, relationTo: "CalendarEvent" },
      { name: "aiDocuments", type: "AiDocument", isList: true, isOptional: false, relationTo: "AiDocument" },
      { name: "aiChatSessions", type: "AiChatSession", isList: true, isOptional: false, relationTo: "AiChatSession" },
      { name: "apiUsageLogs", type: "ApiUsageLog", isList: true, isOptional: false, relationTo: "ApiUsageLog" },
    ],
  },
  EmployeeProfile: {
    name: 'EmployeeProfile',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "userId", type: "String", isList: false, isOptional: false },
      { name: "user", type: "User", isList: false, isOptional: false, relationTo: "User" },
      { name: "department", type: "String", isList: false, isOptional: true },
      { name: "designation", type: "String", isList: false, isOptional: true },
      { name: "joiningDate", type: "DateTime", isList: false, isOptional: true },
      { name: "salary", type: "Float", isList: false, isOptional: true },
      { name: "status", type: "String", isList: false, isOptional: false, default: "ACTIVE", enumValues: ["ACTIVE","ON_LEAVE","TERMINATED"], comment: "ACTIVE, ON_LEAVE, TERMINATED" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "documents", type: "EmployeeDocument", isList: true, isOptional: false, relationTo: "EmployeeDocument" },
      { name: "attendances", type: "Attendance", isList: true, isOptional: false, relationTo: "Attendance" },
      { name: "leaveRequests", type: "LeaveRequest", isList: true, isOptional: false, relationTo: "LeaveRequest" },
      { name: "activities", type: "ActivityLog", isList: true, isOptional: false, relationTo: "ActivityLog" },
      { name: "reviews", type: "PerformanceReview", isList: true, isOptional: false, relationTo: "PerformanceReview" },
      { name: "payrolls", type: "Payroll", isList: true, isOptional: false, relationTo: "Payroll" },
      { name: "driverProfile", type: "DriverProfile", isList: false, isOptional: true, relationTo: "DriverProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  EmployeeDocument: {
    name: 'EmployeeDocument',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false, comment: "e.g., Emirates ID, Resume, Contract" },
      { name: "category", type: "String", isList: false, isOptional: false, enumValues: ["ID","CONTRACT","RESUME","OTHER"], comment: "ID, CONTRACT, RESUME, OTHER" },
      { name: "fileUrl", type: "String", isList: false, isOptional: false },
      { name: "uploadedAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
    ],
  },
  Attendance: {
    name: 'Attendance',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "dateStr", type: "String", isList: false, isOptional: false, comment: "Format: YYYY-MM-DD" },
      { name: "checkIn", type: "DateTime", isList: false, isOptional: true },
      { name: "checkOut", type: "DateTime", isList: false, isOptional: true },
      { name: "status", type: "String", isList: false, isOptional: false, default: "PRESENT", enumValues: ["PRESENT","LATE","ABSENT","ON_LEAVE"], comment: "PRESENT, LATE, ABSENT, ON_LEAVE" },
      { name: "checkoutSummary", type: "String", isList: false, isOptional: true },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  LeaveRequest: {
    name: 'LeaveRequest',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "startDate", type: "DateTime", isList: false, isOptional: false },
      { name: "endDate", type: "DateTime", isList: false, isOptional: false },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["SICK","CASUAL","ANNUAL","UNPAID"], comment: "SICK, CASUAL, ANNUAL, UNPAID" },
      { name: "status", type: "String", isList: false, isOptional: false, default: "PENDING", enumValues: ["PENDING","APPROVED","REJECTED"], comment: "PENDING, APPROVED, REJECTED" },
      { name: "reason", type: "String", isList: false, isOptional: true },
      { name: "approvedAt", type: "DateTime", isList: false, isOptional: true },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  ActivityLog: {
    name: 'ActivityLog',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "description", type: "String", isList: false, isOptional: false },
      { name: "category", type: "String", isList: false, isOptional: false, enumValues: ["WORK","MEETING","COFFEE_BREAK","CALL","OTHER"], comment: "WORK, MEETING, COFFEE_BREAK, CALL, OTHER" },
      { name: "logTime", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "startTime", type: "DateTime", isList: false, isOptional: true },
      { name: "endTime", type: "DateTime", isList: false, isOptional: true },
      { name: "duration", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  PerformanceReview: {
    name: 'PerformanceReview',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "reviewDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "rating", type: "Int", isList: false, isOptional: false, comment: "1-5 stars" },
      { name: "feedback", type: "String", isList: false, isOptional: false },
      { name: "reviewedById", type: "String", isList: false, isOptional: false },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Property: {
    name: 'Property',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "title", type: "String", isList: false, isOptional: false },
      { name: "description", type: "String", isList: false, isOptional: true },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["APARTMENT","VILLA","COMMERCIAL","PLOT"], comment: "APARTMENT, VILLA, COMMERCIAL, PLOT, etc." },
      { name: "status", type: "String", isList: false, isOptional: false, enumValues: ["DRAFT","PUBLISHED","SOLD","RENTED","AVAILABLE"], comment: "DRAFT, PUBLISHED, SOLD, RENTED, AVAILABLE" },
      { name: "listingType", type: "String", isList: false, isOptional: false, default: "SALE", enumValues: ["RENT","SALE"], comment: "RENT, SALE" },
      { name: "price", type: "Float", isList: false, isOptional: false },
      { name: "location", type: "String", isList: false, isOptional: false },
      { name: "bedrooms", type: "Int", isList: false, isOptional: true },
      { name: "bathrooms", type: "Int", isList: false, isOptional: true },
      { name: "areaSqft", type: "Float", isList: false, isOptional: true },
      { name: "images", type: "String", isList: true, isOptional: false, comment: "Array of image URLs" },
      { name: "amenities", type: "String", isList: true, isOptional: false, comment: "Array of amenities, e.g. [\"Pool\", \"Gym\", \"Security\"]" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "assignedToId", type: "String", isList: false, isOptional: true },
      { name: "assignedTo", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "ownerId", type: "String", isList: false, isOptional: true },
      { name: "owner", type: "Owner", isList: false, isOptional: true, relationTo: "Owner" },
      { name: "clientInterests", type: "ClientPropertyInterest", isList: true, isOptional: false, relationTo: "ClientPropertyInterest" },
      { name: "clientViewings", type: "ClientViewing", isList: true, isOptional: false, relationTo: "ClientViewing" },
      { name: "priceHistory", type: "PropertyPriceHistory", isList: true, isOptional: false, relationTo: "PropertyPriceHistory" },
      { name: "keyTracker", type: "KeyTracker", isList: false, isOptional: true, relationTo: "KeyTracker" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Lead: {
    name: 'Lead',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false },
      { name: "email", type: "String", isList: false, isOptional: true },
      { name: "phone", type: "String", isList: false, isOptional: true },
      { name: "source", type: "String", isList: false, isOptional: true, default: "DIRECT", enumValues: ["ZILLOW","PROPERTY_FINDER","FACEBOOK","DIRECT","WEBSITE"], comment: "ZILLOW, PROPERTY_FINDER, FACEBOOK, DIRECT, WEBSITE, etc." },
      { name: "status", type: "String", isList: false, isOptional: false, default: "NEW", enumValues: ["NEW","CONTACTED","ENGAGED","DISQUALIFIED","CLOSED"], comment: "NEW, CONTACTED, ENGAGED, DISQUALIFIED, CLOSED" },
      { name: "score", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "isDuplicate", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "duplicateOfId", type: "String", isList: false, isOptional: true },
      { name: "notes", type: "String", isList: false, isOptional: true },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "assignedToId", type: "String", isList: false, isOptional: true },
      { name: "assignedTo", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "activities", type: "LeadActivity", isList: true, isOptional: false, relationTo: "LeadActivity" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Client: {
    name: 'Client',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false },
      { name: "email", type: "String", isList: false, isOptional: true },
      { name: "phone", type: "String", isList: false, isOptional: false },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["BUYER","SELLER","INVESTOR"], comment: "BUYER, SELLER, INVESTOR" },
      { name: "address", type: "String", isList: false, isOptional: true },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "assignedToId", type: "String", isList: false, isOptional: true },
      { name: "assignedTo", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "stage", type: "String", isList: false, isOptional: false, default: "INQUIRY", enumValues: ["INQUIRY","VIEWING","OFFER","CLOSED"], comment: "INQUIRY, VIEWING, OFFER, CLOSED" },
      { name: "budget", type: "Float", isList: false, isOptional: true },
      { name: "preferences", type: "String", isList: false, isOptional: true, comment: "e.g. \"3 Bed, DHA Lahore\"" },
      { name: "interestedProperties", type: "ClientPropertyInterest", isList: true, isOptional: false, relationTo: "ClientPropertyInterest" },
      { name: "viewings", type: "ClientViewing", isList: true, isOptional: false, relationTo: "ClientViewing" },
      { name: "communications", type: "ClientCommunication", isList: true, isOptional: false, relationTo: "ClientCommunication" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Task: {
    name: 'Task',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "title", type: "String", isList: false, isOptional: false },
      { name: "description", type: "String", isList: false, isOptional: true },
      { name: "status", type: "String", isList: false, isOptional: false, default: "PENDING", enumValues: ["PENDING","IN_PROGRESS","COMPLETED"], comment: "PENDING, IN_PROGRESS, COMPLETED" },
      { name: "dueDate", type: "DateTime", isList: false, isOptional: true },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "assignedToId", type: "String", isList: false, isOptional: true },
      { name: "assignedTo", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "createdById", type: "String", isList: false, isOptional: true },
      { name: "createdBy", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Owner: {
    name: 'Owner',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false },
      { name: "email", type: "String", isList: false, isOptional: true },
      { name: "phone", type: "String", isList: false, isOptional: false },
      { name: "status", type: "String", isList: false, isOptional: false, default: "ACTIVE", enumValues: ["ACTIVE","INACTIVE"], comment: "ACTIVE, INACTIVE" },
      { name: "kycVerified", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "kycNotes", type: "String", isList: false, isOptional: true },
      { name: "commissionRate", type: "Float", isList: false, isOptional: true, comment: "percentage, e.g. 5.0" },
      { name: "agreementUrl", type: "String", isList: false, isOptional: true },
      { name: "agreementExpiry", type: "DateTime", isList: false, isOptional: true },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "assignedToId", type: "String", isList: false, isOptional: true },
      { name: "assignedTo", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "properties", type: "Property", isList: true, isOptional: false, relationTo: "Property", comment: "One Owner can list many properties" },
      { name: "communications", type: "OwnerCommunication", isList: true, isOptional: false, relationTo: "OwnerCommunication" },
      { name: "documents", type: "OwnerDocument", isList: true, isOptional: false, relationTo: "OwnerDocument" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  OwnerCommunication: {
    name: 'OwnerCommunication',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["CALL","EMAIL","MEETING","WHATSAPP"], comment: "CALL, EMAIL, MEETING, WHATSAPP" },
      { name: "summary", type: "String", isList: false, isOptional: false },
      { name: "date", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "ownerId", type: "String", isList: false, isOptional: false },
      { name: "owner", type: "Owner", isList: false, isOptional: false, relationTo: "Owner" },
    ],
  },
  OwnerDocument: {
    name: 'OwnerDocument',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false, comment: "Emirates ID, Title Deed, POA" },
      { name: "fileUrl", type: "String", isList: false, isOptional: false },
      { name: "uploadedAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "ownerId", type: "String", isList: false, isOptional: false },
      { name: "owner", type: "Owner", isList: false, isOptional: false, relationTo: "Owner" },
    ],
  },
  ClientPropertyInterest: {
    name: 'ClientPropertyInterest',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "clientId", type: "String", isList: false, isOptional: false },
      { name: "client", type: "Client", isList: false, isOptional: false, relationTo: "Client" },
      { name: "propertyId", type: "String", isList: false, isOptional: false },
      { name: "property", type: "Property", isList: false, isOptional: false, relationTo: "Property" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  ClientViewing: {
    name: 'ClientViewing',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "viewingDate", type: "DateTime", isList: false, isOptional: false },
      { name: "feedback", type: "String", isList: false, isOptional: true },
      { name: "status", type: "String", isList: false, isOptional: false, default: "SCHEDULED", enumValues: ["SCHEDULED","COMPLETED","CANCELLED"], comment: "SCHEDULED, COMPLETED, CANCELLED" },
      { name: "clientId", type: "String", isList: false, isOptional: false },
      { name: "client", type: "Client", isList: false, isOptional: false, relationTo: "Client" },
      { name: "propertyId", type: "String", isList: false, isOptional: false },
      { name: "property", type: "Property", isList: false, isOptional: false, relationTo: "Property" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  ClientCommunication: {
    name: 'ClientCommunication',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["CALL","EMAIL","MEETING","WHATSAPP"], comment: "CALL, EMAIL, MEETING, WHATSAPP" },
      { name: "summary", type: "String", isList: false, isOptional: false },
      { name: "date", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "clientId", type: "String", isList: false, isOptional: false },
      { name: "client", type: "Client", isList: false, isOptional: false, relationTo: "Client" },
    ],
  },
  Payroll: {
    name: 'Payroll',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "month", type: "String", isList: false, isOptional: false, comment: "Format: YYYY-MM" },
      { name: "baseSalary", type: "Float", isList: false, isOptional: false },
      { name: "allowances", type: "Float", isList: false, isOptional: false, default: "0" },
      { name: "deductions", type: "Float", isList: false, isOptional: false, default: "0" },
      { name: "netSalary", type: "Float", isList: false, isOptional: false },
      { name: "status", type: "String", isList: false, isOptional: false, default: "UNPAID", enumValues: ["UNPAID","PAID"], comment: "UNPAID, PAID" },
      { name: "paidAt", type: "DateTime", isList: false, isOptional: true },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  PropertyPriceHistory: {
    name: 'PropertyPriceHistory',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "price", type: "Float", isList: false, isOptional: false },
      { name: "changeDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "propertyId", type: "String", isList: false, isOptional: false },
      { name: "property", type: "Property", isList: false, isOptional: false, relationTo: "Property" },
    ],
  },
  Document: {
    name: 'Document',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false },
      { name: "category", type: "String", isList: false, isOptional: false, comment: "e.g. SALES, TENANCY, KYC, CORPORATE, OTHER" },
      { name: "fileUrl", type: "String", isList: false, isOptional: false },
      { name: "version", type: "Int", isList: false, isOptional: false, default: "1" },
      { name: "tags", type: "String", isList: true, isOptional: false, comment: "Tag keywords" },
      { name: "expiryDate", type: "DateTime", isList: false, isOptional: true },
      { name: "isExpired", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "accessRole", type: "String", isList: false, isOptional: false, default: "VIEWER", enumValues: ["VIEWER","AGENT","ADMIN","SUPER_ADMIN"], comment: "VIEWER, AGENT, ADMIN, SUPER_ADMIN" },
      { name: "targetRoles", type: "String", isList: true, isOptional: false },
      { name: "targetUserIds", type: "String", isList: true, isOptional: false },
      { name: "writeRoles", type: "String", isList: true, isOptional: false },
      { name: "writeUserIds", type: "String", isList: true, isOptional: false },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdById", type: "String", isList: false, isOptional: false },
      { name: "createdBy", type: "User", isList: false, isOptional: false, relationTo: "User" },
      { name: "versions", type: "DocumentVersion", isList: true, isOptional: false, relationTo: "DocumentVersion" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  DocumentVersion: {
    name: 'DocumentVersion',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "version", type: "Int", isList: false, isOptional: false },
      { name: "fileUrl", type: "String", isList: false, isOptional: false },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "documentId", type: "String", isList: false, isOptional: false },
      { name: "document", type: "Document", isList: false, isOptional: false, relationTo: "Document" },
      { name: "updatedById", type: "String", isList: false, isOptional: false },
      { name: "updatedBy", type: "User", isList: false, isOptional: false, relationTo: "User" },
    ],
  },
  DriverProfile: {
    name: 'DriverProfile',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "licenseNumber", type: "String", isList: false, isOptional: false },
      { name: "status", type: "String", isList: false, isOptional: false, default: "AVAILABLE", enumValues: ["AVAILABLE","BUSY","OFF_DUTY"], comment: "AVAILABLE, BUSY, OFF_DUTY" },
      { name: "employeeProfileId", type: "String", isList: false, isOptional: false },
      { name: "employeeProfile", type: "EmployeeProfile", isList: false, isOptional: false, relationTo: "EmployeeProfile" },
      { name: "schedules", type: "LogisticsSchedule", isList: true, isOptional: false, relationTo: "LogisticsSchedule" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Vehicle: {
    name: 'Vehicle',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "modelName", type: "String", isList: false, isOptional: false },
      { name: "plateNumber", type: "String", isList: false, isOptional: false },
      { name: "status", type: "String", isList: false, isOptional: false, default: "ACTIVE", enumValues: ["ACTIVE","MAINTENANCE","OUT_OF_SERVICE"], comment: "ACTIVE, MAINTENANCE, OUT_OF_SERVICE" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "maintenanceRequests", type: "VehicleMaintenance", isList: true, isOptional: false, relationTo: "VehicleMaintenance" },
      { name: "schedules", type: "LogisticsSchedule", isList: true, isOptional: false, relationTo: "LogisticsSchedule" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  VehicleMaintenance: {
    name: 'VehicleMaintenance',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "description", type: "String", isList: false, isOptional: false },
      { name: "cost", type: "Float", isList: false, isOptional: true },
      { name: "status", type: "String", isList: false, isOptional: false, default: "PENDING", enumValues: ["PENDING","COMPLETED","CANCELLED"], comment: "PENDING, COMPLETED, CANCELLED" },
      { name: "requestDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "completionDate", type: "DateTime", isList: false, isOptional: true },
      { name: "vehicleId", type: "String", isList: false, isOptional: false },
      { name: "vehicle", type: "Vehicle", isList: false, isOptional: false, relationTo: "Vehicle" },
    ],
  },
  LogisticsSchedule: {
    name: 'LogisticsSchedule',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "visitDate", type: "DateTime", isList: false, isOptional: false },
      { name: "pickupLocation", type: "String", isList: false, isOptional: false },
      { name: "dropLocation", type: "String", isList: false, isOptional: false },
      { name: "status", type: "String", isList: false, isOptional: false, default: "SCHEDULED", enumValues: ["SCHEDULED","IN_TRANSIT","COMPLETED","CANCELLED"], comment: "SCHEDULED, IN_TRANSIT, COMPLETED, CANCELLED" },
      { name: "driverId", type: "String", isList: false, isOptional: true },
      { name: "driver", type: "DriverProfile", isList: false, isOptional: true, relationTo: "DriverProfile" },
      { name: "vehicleId", type: "String", isList: false, isOptional: true },
      { name: "vehicle", type: "Vehicle", isList: false, isOptional: true, relationTo: "Vehicle" },
      { name: "viewingId", type: "String", isList: false, isOptional: true, comment: "Dynamic viewing linkage" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  KeyTracker: {
    name: 'KeyTracker',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "keyTag", type: "String", isList: false, isOptional: false, comment: "e.g. KEY-DHA-42" },
      { name: "status", type: "String", isList: false, isOptional: false, default: "IN_OFFICE", enumValues: ["IN_OFFICE","CHECKED_OUT","LOST"], comment: "IN_OFFICE, CHECKED_OUT, LOST" },
      { name: "propertyId", type: "String", isList: false, isOptional: false },
      { name: "property", type: "Property", isList: false, isOptional: false, relationTo: "Property" },
      { name: "checkouts", type: "KeyCheckout", isList: true, isOptional: false, relationTo: "KeyCheckout" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  KeyCheckout: {
    name: 'KeyCheckout',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "checkoutDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "returnDate", type: "DateTime", isList: false, isOptional: true },
      { name: "notes", type: "String", isList: false, isOptional: true },
      { name: "keyId", type: "String", isList: false, isOptional: false },
      { name: "key", type: "KeyTracker", isList: false, isOptional: false, relationTo: "KeyTracker" },
      { name: "userId", type: "String", isList: false, isOptional: false },
      { name: "user", type: "User", isList: false, isOptional: false, relationTo: "User" },
    ],
  },
  LeadActivity: {
    name: 'LeadActivity',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["CALL","EMAIL","NOTES","STATUS_CHANGE"], comment: "CALL, EMAIL, NOTES, STATUS_CHANGE" },
      { name: "description", type: "String", isList: false, isOptional: false },
      { name: "activityDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "leadId", type: "String", isList: false, isOptional: false },
      { name: "lead", type: "Lead", isList: false, isOptional: false, relationTo: "Lead" },
    ],
  },
  ChatRoom: {
    name: 'ChatRoom',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: true, comment: "e.g. \"General Team Chat\"" },
      { name: "isGroup", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "isSystem", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "systemUserId", type: "String", isList: false, isOptional: true, comment: "Links private bot logs to a specific user" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "members", type: "User", isList: true, isOptional: false, relationTo: "User" },
      { name: "messages", type: "Message", isList: true, isOptional: false, relationTo: "Message" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Message: {
    name: 'Message',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "content", type: "String", isList: false, isOptional: false },
      { name: "isSystem", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "chatRoomId", type: "String", isList: false, isOptional: false },
      { name: "chatRoom", type: "ChatRoom", isList: false, isOptional: false, relationTo: "ChatRoom" },
      { name: "senderId", type: "String", isList: false, isOptional: true, comment: "Null for system bot alerts" },
      { name: "sender", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  CalendarEvent: {
    name: 'CalendarEvent',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "title", type: "String", isList: false, isOptional: false },
      { name: "description", type: "String", isList: false, isOptional: true },
      { name: "startTime", type: "DateTime", isList: false, isOptional: false },
      { name: "endTime", type: "DateTime", isList: false, isOptional: false },
      { name: "location", type: "String", isList: false, isOptional: true },
      { name: "isPrivate", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "targetRoles", type: "String", isList: true, isOptional: false, comment: "e.g. [\"HR\", \"FINANCE\"] for department meetings" },
      { name: "targetUserIds", type: "String", isList: true, isOptional: false, comment: "e.g. [\"user-uuid-1\"] for specific invites" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdById", type: "String", isList: false, isOptional: false },
      { name: "createdBy", type: "User", isList: false, isOptional: false, relationTo: "User" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  AiDocument: {
    name: 'AiDocument',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false, comment: "e.g., \"DHA-Listing-Policy-2026.pdf\"" },
      { name: "fileUrl", type: "String", isList: false, isOptional: true, comment: "Local path or URL" },
      { name: "fileType", type: "String", isList: false, isOptional: false, enumValues: ["PDF","TXT","NOTE"], comment: "PDF, TXT, NOTE, etc." },
      { name: "fileSize", type: "Int", isList: false, isOptional: true, comment: "in bytes" },
      { name: "version", type: "Int", isList: false, isOptional: false, default: "1" },
      { name: "metadata", type: "Json", isList: false, isOptional: true, comment: "Author, access permission roles, duplicate status" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdById", type: "String", isList: false, isOptional: false },
      { name: "createdBy", type: "User", isList: false, isOptional: false, relationTo: "User" },
      { name: "chunks", type: "AiDocumentChunk", isList: true, isOptional: false, relationTo: "AiDocumentChunk" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  AiDocumentChunk: {
    name: 'AiDocumentChunk',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "content", type: "String", isList: false, isOptional: false },
      { name: "embedding", type: "Unsupported", isList: false, isOptional: false, relationTo: "Unsupported" },
      { name: "metadata", type: "Json", isList: false, isOptional: true, comment: "Page number, paragraph index, citation, etc." },
      { name: "documentId", type: "String", isList: false, isOptional: false },
      { name: "document", type: "AiDocument", isList: false, isOptional: false, relationTo: "AiDocument" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  AiChatSession: {
    name: 'AiChatSession',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "title", type: "String", isList: false, isOptional: false },
      { name: "userId", type: "String", isList: false, isOptional: false },
      { name: "user", type: "User", isList: false, isOptional: false, relationTo: "User" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "messages", type: "Json", isList: false, isOptional: false, comment: "Array of messages: [{role: \"user\" | \"model\", content: string, toolExecuted?: string, toolData?: any, citations?: any[], createdAt: string}]" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  IntegrationConfig: {
    name: 'IntegrationConfig',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "type", type: "String", isList: false, isOptional: false, enumValues: ["EMAIL","WHATSAPP","SMS","VOICE","PORTAL_FEED","GOOGLE_DRIVE","GOOGLE_MAPS"], comment: "EMAIL, WHATSAPP, SMS, VOICE, PORTAL_FEED, GOOGLE_DRIVE, GOOGLE_MAPS" },
      { name: "isEnabled", type: "Boolean", isList: false, isOptional: false, default: "false" },
      { name: "credentials", type: "Json", isList: false, isOptional: false, comment: "API keys, client secrets, Twilio numbers, etc." },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  CommunicationTemplate: {
    name: 'CommunicationTemplate',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "name", type: "String", isList: false, isOptional: false, comment: "e.g., \"Welcome Lead Email\", \"OTP Reminder\"" },
      { name: "subject", type: "String", isList: false, isOptional: true, comment: "Dynamic subject line if Email" },
      { name: "content", type: "String", isList: false, isOptional: false, comment: "Variable-supported body text: e.g. {{leadName}}" },
      { name: "channel", type: "String", isList: false, isOptional: false, enumValues: ["EMAIL","WHATSAPP","SMS"], comment: "EMAIL, WHATSAPP, SMS" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  IntegrationLog: {
    name: 'IntegrationLog',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "channel", type: "String", isList: false, isOptional: false, enumValues: ["EMAIL","WHATSAPP","SMS","VOICE","PORTAL"], comment: "EMAIL, WHATSAPP, SMS, VOICE, PORTAL" },
      { name: "direction", type: "String", isList: false, isOptional: false, enumValues: ["INBOUND","OUTBOUND"], comment: "INBOUND, OUTBOUND" },
      { name: "status", type: "String", isList: false, isOptional: false, enumValues: ["SUCCESS","FAILED","PENDING"], comment: "SUCCESS, FAILED, PENDING" },
      { name: "payload", type: "Json", isList: false, isOptional: true, comment: "Full transaction payload details" },
      { name: "errorMessage", type: "String", isList: false, isOptional: true },
      { name: "leadId", type: "String", isList: false, isOptional: true, comment: "Optional foreign link" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  AiMemoryVector: {
    name: 'AiMemoryVector',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "category", type: "String", isList: false, isOptional: false, comment: "e.g. CLIENT_PREFERENCE, EMPLOYEE_PERFORMANCE, OPERATIONAL_NOTE" },
      { name: "content", type: "String", isList: false, isOptional: false },
      { name: "embedding", type: "Unsupported", isList: false, isOptional: false, relationTo: "Unsupported" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "clientId", type: "String", isList: false, isOptional: true },
      { name: "userId", type: "String", isList: false, isOptional: true },
      { name: "propertyId", type: "String", isList: false, isOptional: true },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
  Subscription: {
    name: 'Subscription',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "plan", type: "String", isList: false, isOptional: false, default: "STANDARD", enumValues: ["STANDARD","PREMIUM","ENTERPRISE"], comment: "STANDARD, PREMIUM, ENTERPRISE" },
      { name: "status", type: "String", isList: false, isOptional: false, default: "ACTIVE", enumValues: ["ACTIVE","OVERDUE","SUSPENDED"], comment: "ACTIVE, OVERDUE, SUSPENDED" },
      { name: "monthlyPrice", type: "Float", isList: false, isOptional: false, default: "3000.0", comment: "Monthly rent in AED" },
      { name: "currency", type: "String", isList: false, isOptional: false, default: "AED" },
      { name: "startDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "endDate", type: "DateTime", isList: false, isOptional: true },
      { name: "nextBillingDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "paymentStatus", type: "String", isList: false, isOptional: false, default: "PAID", enumValues: ["PAID","PARTIAL","UNPAID"], comment: "PAID, PARTIAL, UNPAID" },
      { name: "amountPaidThisCycle", type: "Float", isList: false, isOptional: false, default: "0.0" },
      { name: "amountPending", type: "Float", isList: false, isOptional: false, default: "3000.0" },
      { name: "lastPaymentDate", type: "DateTime", isList: false, isOptional: true },
      { name: "billingCycle", type: "String", isList: false, isOptional: false, default: "MONTHLY", enumValues: ["MONTHLY","YEARLY"], comment: "MONTHLY, YEARLY" },
      { name: "contractTerms", type: "String", isList: false, isOptional: true },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
      { name: "payments", type: "SubscriptionPayment", isList: true, isOptional: false, relationTo: "SubscriptionPayment" },
    ],
  },
  SubscriptionPayment: {
    name: 'SubscriptionPayment',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "subscriptionId", type: "String", isList: false, isOptional: false },
      { name: "subscription", type: "Subscription", isList: false, isOptional: false, relationTo: "Subscription" },
      { name: "amount", type: "Float", isList: false, isOptional: false },
      { name: "currency", type: "String", isList: false, isOptional: false, default: "AED" },
      { name: "status", type: "String", isList: false, isOptional: false, enumValues: ["SUCCESS","FAILED","PENDING"], comment: "SUCCESS, FAILED, PENDING" },
      { name: "paymentDate", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "billingPeriod", type: "String", isList: false, isOptional: false, comment: "e.g. \"2026-05\" (YYYY-MM)" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  ApiUsageLog: {
    name: 'ApiUsageLog',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "userId", type: "String", isList: false, isOptional: true },
      { name: "user", type: "User", isList: false, isOptional: true, relationTo: "User" },
      { name: "serviceName", type: "String", isList: false, isOptional: false, comment: "\"Ollama\" | \"Gemini\" | \"OpenAI\"" },
      { name: "modelName", type: "String", isList: false, isOptional: false, comment: "e.g., \"gemini-2.0-flash\"" },
      { name: "type", type: "String", isList: false, isOptional: false, comment: "\"TEXT_GENERATION\" | \"EMBEDDING\"" },
      { name: "requestCount", type: "Int", isList: false, isOptional: false, default: "1" },
      { name: "promptTokens", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "completionTokens", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "totalTokens", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  AiPendingApproval: {
    name: 'AiPendingApproval',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "userId", type: "String", isList: false, isOptional: false },
      { name: "userRole", type: "String", isList: false, isOptional: false },
      { name: "userMessage", type: "String", isList: false, isOptional: false },
      { name: "sessionId", type: "String", isList: false, isOptional: true },
      { name: "callPersona", type: "String", isList: false, isOptional: true },
      { name: "executionGraph", type: "Json", isList: false, isOptional: false },
      { name: "toolCallIndex", type: "Int", isList: false, isOptional: false, default: "0" },
      { name: "executedResults", type: "Json", isList: false, isOptional: false, default: "[]" },
      { name: "historyJson", type: "Json", isList: false, isOptional: false, default: "[]" },
      { name: "expiresAt", type: "DateTime", isList: false, isOptional: false },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
    ],
  },
  AiActiveDraft: {
    name: 'AiActiveDraft',
    fields: [
      { name: "id", type: "String", isList: false, isOptional: false, default: "uuid()" },
      { name: "organizationId", type: "String", isList: false, isOptional: false },
      { name: "organization", type: "Organization", isList: false, isOptional: false, relationTo: "Organization" },
      { name: "userId", type: "String", isList: false, isOptional: false },
      { name: "draftType", type: "String", isList: false, isOptional: false },
      { name: "draftData", type: "Json", isList: false, isOptional: false },
      { name: "expiresAt", type: "DateTime", isList: false, isOptional: false },
      { name: "createdAt", type: "DateTime", isList: false, isOptional: false, default: "now()" },
      { name: "updatedAt", type: "DateTime", isList: false, isOptional: false },
    ],
  },
};
